Hospital/TEST APPLICATION/Models/Patient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TEST_APPLICATION.Models
{
    [Table("Patient")]
    [Serializable]
    public class Patient
    {
        public int Id { get; set; }
        [Required]
        public string IdCardNumber { get; set; }
        [Required]
        public string FullName { get; set; }        
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
    }
}

Hospital/TEST APPLICATION/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TEST_APPLICATION.Data;
using TEST_APPLICATION.Models;
using TEST_APPLICATION.Models.ViewModel;

namespace TEST_APPLICATION.Controllers
{
    public class PatientsController : Controller
    {
        private readonly HospitalContext _context;

        public PatientsController(HospitalContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string request)
        {
            var patients = await _context.Patients.ToListAsync();

            if (!String.IsNullOrEmpty(request))
            {
                patients = patients.Where(s => s.FullName.Contains(request) || s.IdCardNumber.Contains(request)).ToList();
            }

            return View(patients);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patients
                .FirstOrDefaultAsync(m => m.Id == id);

            if (patient == null)
            {
                return NotFound();
            }   
            
            var visits = await _context.Visits.Where(item => item.PatientId == patient.Id).ToListAsync() as IEnumerable<Visit>;
            var viewModelVisits = new List<ViewModelVisit>();

            
            if (visits != null)
            {
                foreach (var item in visits)
                {
                    var diagnosis = _context.Diagnoses.Where(x => x.Id == item.DiagnosisId).FirstOrDefault();
                    var doctor = _context.Doctors.Where(x => x.Id == item.DoctorId).FirstOrDefault();

                    viewModelVisits.Add(new ViewModelVisit() 
                    { 
                        Id = item.Id,
                        Complaints = item.Complaints,
                        Doctor = doctor.FullName + '(' + doctor.Specialty + ')',
                        Diagnosis = diagnosis.Name,
                        DateVisit = item.DateVisit,

                    });
                }
            }

            var detailsViewModel = new ViewModelDetailsPatient()
            {
                Patient = patient,
                Visits = viewModelVisits
            };

            return View(detailsViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return PartialView();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdCardNumber,FullName,Address,PhoneNumber")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                _context.Add(patient);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(patient);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {   
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patients.FindAsync(id);
            if (patient == null)
            {
                return NotFound();
            }
            return PartialView(patient);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdCardNumber,FullName,Address,PhoneNumber")] Patient patient)
        {
            if (id != patient.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patient);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientExists(patient.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(patient);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (patient == null)
            {
                return NotFound();
            }

            return PartialView(patient);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var patient = await _context.Patients.FindAsync(id);
            _context.Patients.Remove(patient);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientExists(int id)
        {
            return _context.Patients.Any(e => e.Id == id);
        }
    }
}

Hospital/TEST APPLICATION/Controllers/VisitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TEST_APPLICATION.Data;
using TEST_APPLICATION.Models;

namespace TEST_APPLICATION.Controllers
{
    public class VisitsController : Controller
    {
        private readonly HospitalContext _context;

        public VisitsController(HospitalContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visit = await _context.Visits
                .FirstOrDefaultAsync(m => m.Id == id);
            if (visit == null)
            {
                return NotFound();
            }

            return PartialView(visit);
        }

        [HttpGet]
        public IActionResult Create(int patientId)
        {
            ViewData["PatientId"] = patientId;
            ViewData["Diagnoses"] = _context.Diagnoses.ToList();
            ViewData["Doctors"] = _context.Doctors.ToList();
            return PartialView();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PatientId,DoctorId,DiagnosisId,Complaints,DateVisit")] Visit visit)
        {  
            if (ModelState.IsValid)
            {
                _context.Add(visit);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Patients", new { id = visit.PatientId});
            }
            return View(visit);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["Diagnoses"] = _context.Diagnoses.ToList();
            ViewData["Doctors"] = _context.Doctors.ToList();

            if (id == null)
            {
                return NotFound();
            }

            var visit = await _context.Visits.FindAsync(id);
            if (visit == null)
            {
                return NotFound();
            }
            return PartialView(visit);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PatientId,DoctorId,DiagnosisId,Complaints,DateVisit")] Visit visit)
        {
            if (id != visit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(visit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VisitExists(visit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Patients", new { id = visit.PatientId });
            }
            return View(visit);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visit = await _context.Visits
                .FirstOrDefaultAsync(m => m.Id == id);
            if (visit == null)
            {
                return NotFound();
            }

            return PartialView(visit);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var visit = await _context.Visits.FindAsync(id);
            _context.Visits.Remove(visit);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Patients", new { id = visit.PatientId });
        }

        private bool VisitExists(int id)
        {
            return _context.Visits.Any(e => e.Id == id);
        }
    }
}

Hospital/TEST APPLICATION/Views/Patients/Create.cshtml
@model TEST_APPLICATION.Models.Patient

@{
    ViewData["Title"] = "Add Patient";
}


<div class="modal-content">
    <div class="modal-header">
        <h4>@ViewData["Title"]</h4>
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
    </div>
    <div class="modal-body">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdCardNumber" class="control-label"></label>
                <input asp-for="IdCardNumber" class="form-control" />
                <span asp-validation-for="IdCardNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>            
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hospital/TEST APPLICATION/Views/Patients/Delete.cshtml
@model TEST_APPLICATION.Models.Patient

@{
    ViewData["Title"] = "Delete";
}

<div class="modal-content">
    <div class="modal-header">
        <h4>@ViewData["Title"]</h4>
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
    </div>
    <div class="modal-body">
        <p>Patient Id Card Number @Html.DisplayFor(model => model.IdCardNumber)</p>
        <hr />
        <p>Are you sure you want to delete patient from base?</p>
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>
    </div>
</div>

Hospital/TEST APPLICATION/Views/Patients/Details.cshtml
@model TEST_APPLICATION.Models.ViewModel.ViewModelDetailsPatient

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Patient</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.IdCardNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.IdCardNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.FullName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a class="editPatientBtn" asp-action="Edit" asp-route-id="@Model.Patient.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
<div>
    <h2>Doctor visits</h2>
    @{
        if (Model.Visits != null & Model.Visits.Count() != 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Visits.First().Doctor)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Visits.First().Diagnosis)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Visits.First().Complaints)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Visits.First().DateVisit)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Visits.ToList())
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Doctor)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Diagnosis)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Complaints)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DateVisit)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", "Visits", new { id = item.Id }, new { @class = "editPatientBtn" }) |
                                @Html.ActionLink("Details", "Details", "Visits", new { id = item.Id }, new { @class = "detailsVisitBtn" }) |
                                @Html.ActionLink("Delete", "Delete", "Visits", new { id = item.Id }, new { @class = "deleteVisitBtn" }) 
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>Items not found</p>
        }
    }
    @Html.ActionLink("Create visit", "Create", "Visits", new { patientId = Model.Patient.Id }, new { @class= "createVisitBtn" })    
</div>

@section scripts
{
    <script type="text/javascript">

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".editPatientBtn").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })    

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".createVisitBtn").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".editVisitBtn").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".detailsVisitBtn").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".deleteVisitBtn").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>
}

Hospital/TEST APPLICATION/Views/Patients/Edit.cshtml
@model TEST_APPLICATION.Models.Patient

@{
    ViewData["Title"] = "Edit";
}

<div class="modal-content">
    <div class="modal-header">
        <h4>@ViewData["Title"]</h4>
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
    </div>
    <div class="modal-body">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="IdCardNumber" class="control-label"></label>
                <input asp-for="IdCardNumber" class="form-control" />
                <span asp-validation-for="IdCardNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}



@*<div class="form-group">
    <label class="control-label"></label>
    <select asp-for="AddressId" name="addressId" class="form-control">
        @foreach (var item in @ViewData["addresses"] as List<Address>)
        {
            <option value="@item.Id">@item.AddressLine</option>
        }
    </select>
    <span asp-validation-for="AddressId" class="text-danger"></span>
</div>*@

Hospital/TEST APPLICATION/Views/Patients/Index.cshtml
@model IEnumerable<TEST_APPLICATION.Models.Patient>

@{
    ViewData["Title"] = "Patients";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create" class="createPatientBtn">Add New Patient</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdCardNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdCardNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="editPatientBtn">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="deletePatientBtn">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts
{
    <script type="text/javascript">

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".createPatientBtn").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".editPatientBtn").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".deletePatientBtn").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".createVisitBtn").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>    
}